- lua/cmake-tools/utils.lua
- lua/simpleyaml.lua
So apparently the #2  wasn't 100% ready for merge yet...
There was a broken regex in the simpleyaml library, and the CMakeSelectBuildType command would fail when trying to remove a non-existend build directory.
> Fix bugs with variants

- lua/cmake-tools/config.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/kits.lua
- lua/cmake-tools/utils.lua
- lua/cmake-tools/variants.lua
- plugin/cmake-tools.lua
[Docs](https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html#kit-scan) for CMake Kits.
Currently:
1. Not support Visual Studio.
2. Not support option `preferredGenerator`.
3. Not support option `cmakeSettings`.
> Support CMake Kits

- lua/cmake-tools/init.lua
Move it earlier to make Config functions happy.
> move config:generate_build_directory() to up

- lua/cmake-tools/init.lua
--- CMake open cmake console
function cmake.open()
utils.show_cmake_console(const.cmake_console_size)
end
> open cmake console  should set size

- lua/cmake-tools/kits.lua
Tested with both `cmake-kits.json` and `CMakeKits.json`
> Added Naming Convention

- lua/cmake-tools/init.lua
- lua/cmake-tools/kits.lua
> Added Windows Output fix

- lua/cmake-tools/init.lua
- lua/cmake-tools/kits.lua
Reverts Civitasv/cmake-tools.nvim#40
> Revert "Added Windows Output fix"

- lua/cmake-tools/presets.lua
- According to https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#implicit-preset-includes If CMakePresets.json and CMakeUserPresets.json exists, CMakeUserPresets.json implicitly includes CMakePresets.json
- Fix formatting while at it
- Fixes #30
> Implicitly include CMakePresets.json when parsing CMakeUserPreset.json

- lua/cmake-tools/terminal.lua
> Keep Constant Scrolling

- lua/cmake-tools/init.lua
> bugfix for cmake_regenerate_on_save option

- README.md
Fixed the following typos
- Changed `powerfull` to `powerful`
- Added missing `'`.
> (#86) Fixed typos

- docs/howto.md
- lua/cmake-tools/init.lua
I added this to read coverage data from the build directory. Might also be useful for other data that gets written into build directory.
> added cmake.get_build_directory

- lua/cmake-tools/terminal.lua
- fixed start insert option upon the launch of the terminal
- fixed inverted focus on terminal option
> Fixed start_insert and focus on terminal option

- .github/workflows/main.yml
- .pre-commit-config.yaml
I added stylua to the github workflows and to (pre-commit-config)[https://pre-commit.com/], so that when creating pull requests and run formatting we won't affect previous existing code
> Add format to github actions

- lua/cmake-tools/session.lua
Use lua native io calls to create empty file (replace os.exec('touch'))
> #150 couldn't make stderr distinct from stdout

- lua/cmake-tools/file_picker.lua
See https://github.com/Civitasv/cmake-tools.nvim/issues/109
> Fix telescope extension throw

- lua/cmake-tools/init.lua
Sorry I forgot the defaults :pray:
> Add missing defaults for settings

- docs/howto.md
#108 Update how-to: Add MSBuild errorformat to fix quickfix
> #108 Update how-to: Add MSBuild errorformat to fix quickfix

- lua/cmake-tools/init.lua
See https://github.com/Civitasv/cmake-tools.nvim/issues/100#issuecomment-1657223335
> Fix error on fresh config

- lua/cmake-tools/presets.lua
#120 Fix parsing implicit include presets.
> fix preset decode logic to not skip implicit include

- lua/cmake-tools/init.lua
Fixed regression where the command could only be used with an argument
> Fixed regression of CMakeSelectCwd

- lua/cmake-tools/init.lua
just added a option to use run_test({runAll = true}) to skip selecting tests and run all of them
> feat: add option to run all tests to run_test()

- lua/cmake-tools/terminal.lua
- lua/cmake-tools/test/ctest.lua
as the title says this change appends args when using default runner like in toggleterm.lua
> feat: add arguments to cmd while using terminal.lua

- lua/cmake-tools/init.lua
- lua/cmake-tools/runners/types.lua
- lua/cmake-tools/terminal.lua
- lua/cmake-tools/utils.lua
so this is initial version of lockfile on_exit implementation, it seems to work i just want to share the progress
TODO:
- i'll move lock_file functions to utils and parametrize them
- remove dump from 3rd line
- remove temporary sleep 5 command
- remove special treatment of that full_cmd and implement on_exit properly
- tests
if i'm missing something then please tell me
> feat: initial testing of lockfile and coroutine onexit implementation

- lua/cmake-tools/init.lua
Fixes an path issue on Windows.
> fix: normalize paths in generating autocmd

- lua/cmake-tools/terminal.lua
Fix for #235, adds some conditionals with windows-specific commands for `CMakeRun` command.
> add windows-specific logic to runner code

- lua/cmake-tools/init.lua
I didn't look deep into the cause, but this might fix #268.
> fix(API): Ensure callback is a function

- lua/cmake-tools/terminal.lua
follow up commit for powershell change (see https://github.com/Civitasv/cmake-tools.nvim/pull/264#issuecomment-2425022436)
> Remove file on windows powershell

- lua/cmake-tools/const.lua
- lua/cmake-tools/executors/init.lua
- lua/cmake-tools/runners/init.lua
- lua/cmake-tools/vimux.lua
I use this plugin heavily in my workflow, but I want to use tmux to execute and run my projects. So far, I've gotten some basic functionality working, but there are many bugs that need fixing and features I'd like to add. I am using vimux as the integration layer between neovim and tmux. I created this draft pr to gauge interest in this functionality and get feedback from the maintainers.
> feat(tmux): Execute and Run with tmux
