- lua/cmake-tools/variants.lua
I found the issue you mentioned [here](https://github.com/Civitasv/cmake-tools.nvim/issues/6#issuecomment-1297341842).
The search for the cmake-variants file would ultimately result in a crash, because if no file is found in the current directory, it goes up directories until it finds a suitably named file or crashes and returns the long "../../../" path.
To solve that, I restricted the search to just the current directory.
> Fix bug where search for cmake-variants would crash if none present

- lua/cmake-tools/config.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/presets.lua
New:
- `presets.lua`: I created a function that will parse CMakePresets.json and retrieve their name, since preset you need to pass the name, not the file
- `config.lua`: ah new nil parameter for preset value
Changes:
-`init.lua` - removed references for preset inside `clean`, since it doesn't really help with anything there,
-`init.lua` - changed how to select preset using `vim.ui.select` in `generate` and `build` functions, also I reordered the parameters since it's important to preset comes first than the others.
> fix presets usage

- lua/cmake-tools/const.lua
If dap is not installed on start up you will get an error even if optional dap command is set to nil. Check in const.lua if dap is available before using it.
Here is the error 
```
Error detected while processing /nvim/site/pack/packer/start/cmake-tools.nvim/plugin/cmake-tools.lua:
E5113: Error while calling lua chunk: .../packer/start/cmake-tools.nvim/lua/cmake-tools/const.lua:11:  module 'dap' not found: 
no field package.preload['dap']
no file './dap.lua'
no file '/usr/share/luajit-2.1.0-beta3/dap.lua'
no file '/usr/local/share/lua/5.1/dap.lua'
no file '/usr/local/share/lua/5.1/dap/init.lua'
no file '/usr/share/lua/5.1/dap.lua'
no file '/usr/share/lua/5.1/dap/init.lua'
no file '/nvim/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/dap.lua'
no file …
```
> dap start up error

- lua/cmake-tools/init.lua
- lua/cmake-tools/presets.lua
1. Remove presets with `"hidden" = true` in preset select UI
2. Show preset's `displayName` if it has one
3. Fix infinite loop when building presets with `inherits` field
> Preset Select UI Improvements & Infinite Building Loop Bug Fixes

- lua/cmake-tools/presets.lua
Here is a suggestion to partially tackle #30 .
The proposed changes follow the files included in the top level `CMake[User]Presets.json` file, decodes them and merge their presets into the table that will be later used when the plugin checks for presets.
Thank you for the awesome plugin!
> Handle includes in the top level presets file

- README.md
- lua/cmake-tools/kits.lua
- lua/cmake-tools/variants.lua
* Added Temporary MSVC Support with examples until kit scan is implemented.
* Added Generator Support
* Added Host Architecture Support
* Added Target Architecture Support
@Civitasv, can you test this on linux?
> W.I.P: Multi compiler, generator, architecture support for Windows.

- README.md
- lua/cmake-tools/config.lua
- lua/cmake-tools/const.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/utils.lua
This adds an alternative to soft-linking compile_comands.json by adding functions that users can call in the on_new_config callback for clangd or ccls when using lspconfig.
It sets the compilation database directory to their current preset build directory and updates this path on regen.
The only existing behavior that had to be modified is in utils.show_cmake_console() where it now returns focus to the previous window on open. This is done because when restarting the language server it incorrectly uses the current buffer as the attach target instead of the previously attached buffer.
> Add hooks for clangd and ccls to get compile command directory from preset

- .gitignore
- lua/cmake-tools/init.lua
- lua/cmake-tools/utils.lua
Fix buffer handling in windows 10, and added Autocmd for scrolling buffer output after process completion.
> Fix buffer handling in windows 10, and added Autocmd 

- lua/cmake-tools/init.lua
When debugging the current working directory is set, whereas when running normally the build directory is used
> build_directory ignored when debugging

- README.md
- lua/cmake-tools/const.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/kits.lua
This PR add an option for global kits path.
```lua
cmake_kits_path = nil,
```
If use specify `cmake_kits_path`, it will:
1. If there is no `CMakeKits.json` file at project root directory, it will use this global kits path.
2. Otherwise, it will use local cmake kits file.
> Be able to configure custom path of kits, fix for #50

- lua/cmake-tools/config.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/quickfix.lua
- lua/cmake-tools/terminal.lua
- lua/cmake-tools/utils.lua
- lua/cmake-tools/variants.lua
This is a fix for #60, instead using `on_success` function to chain commands, now I use `&&` to join multiple commands. For example, If uses invoke `CMakeRun`, and not yet `CMakeGenerate` and `CMakeBuild`, it will turn like `cmake -B out/Debug -S . -D CMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && cmake --build out/Debug --target TEST && c
d /home/civitasv/Documents/workflow/test/cmake-test/out/Debug && ./TEST `.
It actually works really good. But it still have a little flaw: For the very first time, users must call `CMakeGenerate` once to generate build system. Then it will work just like quickfix version. I think it's totally acceptable.
> This is a fix for #60

- docs/howto.md
- lua/cmake-tools/const.lua
- lua/cmake-tools/terminal.lua
This is an option that can be provided for other plugins to integrate with cmake_tools. The scrolling buffer can be simply filtered by searching for 'cmake_tools_terminal' filetype directly. For example, using [`hardtime.nvim`](https://github.com/m4xshen/hardtime.nvim). You can specify the ignored/included filetypes for specific operations like: 
```lua
{
"m4xshen/hardtime.nvim",
event = "VeryLazy",
opts = { disabled_filetypes = { "cmake_tools_terminal" },
}
},
```
Ex:
```lua
-- Setter (done on our side)
vim.api.nvim_buf_set_option(<bufnr>, 'filetype', 'cmake_tools_terminal')
-- Getter (in another plugin. Example: hardtime.nvim)
local ft = vim.api.nvim_buf_get_option(<bufnr>, 'filetype')
```
PS: Can be helpful to eliminate the need to create prefixed named for all cmake terminals if we …
> Added new terminal filetype for easier filtering of terminal buffers

- lua/cmake-tools/init.lua
- lua/cmake-tools/session.lua
- lua/cmake-tools/utils.lua
First of all, thanks for the session support! Was on my wish list for this plugin.
I got some errors running master tough, related to creation of the cache directory. On Linux the "touch" command fails if the cache directory does not already exist. So I added some code for that in this PR.
Also made sure that if session.load() returned empty table (first time starting new session), we don't overwrite the config with it as that broke stuff.
Commits in this PR resolved stuff for me, but I have not tested for any other OS.
> Session init fixes

- docs/howto.md
- lua/cmake-tools/init.lua
- lua/cmake-tools/terminal.lua
I added an option to wrap `run` calls in additional arguments.
This allows for example to execute `perf record --call-graph dwarf {executeable}` or `valgrind {program}` with:
```lua
function RunPerf()
local cmake = require "cmake-tools"
cmake.run { wrap_call = { "perf", "record", "--call-graph", "dwarf" } }
end
function RunValgrind()
local cmake = require "cmake-tools"
cmake.run { wrap_call = { "valgrind", "--leak-check=full" } }
end
```
> Add option to wrap cmake.run calls

- lua/cmake-tools/terminal.lua
Fixed terminal focus issues wherein terminal window does not get focused if there is already an existing terminal window and when the start_insert option is disabled
> fixed: terminal window focus issues

- lua/cmake-tools/const.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/quickfix.lua
I added support for [nvim-notify](https://github.com/rcarriga/nvim-notify).
When nvim-notify is installed this add some eyecandy when executing cmake commands that use the quickfix window.
Should pair well with `cmake_quickfix_opts.show  =  "only_on_error"`
[cmake-notify.webm](https://github.com/Civitasv/cmake-tools.nvim/assets/26342294/414a01f1-1b64-4ce1-aee3-945e743c5726)
> nvim-notify support

- lua/cmake-tools/presets.lua
Tested locally by renaming my CMakePresets.json and CMakeUserPresets.json to their kebab-case counter parts, my user preset was still found.  But there was one issue. Upon invocation of CMakeRun, cmake itself complained that it could not find such a preset.
> Fix user preset detection for kebab cased files

- docs/settings.md
- lua/cmake-tools/init.lua
- lua/cmake-tools/terminal.lua
See https://github.com/Civitasv/cmake-tools.nvim/issues/100
It now always runs executeables with absolute path. But this should be ok.
> Allow working directory to specified when running executables

- lua/cmake-tools/environment.lua
- lua/cmake-tools/file_picker.lua
- lua/simpleyaml.lua
Neovim is generally used with LuaJIT which [offers a set of extensions over Lua 5.1](http://luajit.org/extensions.html), including `goto`. However, Neovim can also be [built using plain Lua 5.1](https://github.com/neovim/neovim/blob/0211f889b9538f7df5fbcb06273d273fb071efff/cmake.deps/deps.txt#L10C1-L10C49). To allow the use of Neovim and cmake-tools.nvim on ISA's which are not supported by LuaJIT, it would be useful to keep the code compatible to plain Lua.
This PR removes all usages of `goto` and replaces them with simple conditionals.
> Remove goto statements to ensure compatibility with (plain) Lua 5.1

- lua/cmake-tools/presets.lua
The path will be concatenated twice as the includes will already contain the parent path.
(See #129)
> Fixed preset.decode creating wrong preset paths

- lua/cmake-tools/init.lua
Right now, the absolute working_dir path is concatenated again with the absolute build_directory path, which results in an invalid file path and the symlink not being created. The build_directory will be already an absolute path being constructed using the working_dir.
> Fix compile_commands.json soft link creation

- lua/cmake-tools/init.lua
- lua/cmake-tools/utils.lua
the paths on windows are `\` yet the  `get_path` function used the `/` seperator.
> Fix compatibility with windows path

- lua/cmake-tools/init.lua
Comparison was done without escaping the dash
characters. This resulted in the argument
--compile-commands-dir being added to clangd
command multiple times.
> Fix broken string.find in clangd_on_new_config

- lua/cmake-tools/init.lua
- plugin/cmake-tools.lua
The CMakeSelectCwd command now accepts an optional argument which, if given, will set the CWD to the path of the arg. If no argument is given, the previous behavior applies.
> Setting cwd with command args

- lua/cmake-tools/session.lua
When a session is loaded, it is assumed that
the build directory path is relative to the
project/cwd. However, when the session is saved,
then the build directory is serialized as an
absolute path. This caused the resulting path to
be "project root" + "full path to build directory":
/path/to/project//path/to/project/build/
This fixes the issue by serializing the build
directory as relative the project root.
> Fix broken build directory in session

- lua/cmake-tools/init.lua
When i used this plugin and changed the build type, it only took affect after restarting vim (restarting clangd did not help)
After looking at the code i found it only adds the compile commands path once, and after that it never updates it.
This pull request makes it so every time we update the build type/preset, it will remove any flag for a compile commands, and add the updated one, to ensure it is the only one passed to clangd.
This allows me to change from release to debug without restarting neovim, and seeing the changes happen immediately.
> Fix the clangd update to remove the old arg and add the new one

- lua/cmake-tools/init.lua
A buildPreset can have a configurePreset associated with it. When changing the buildPreset, the configurePreset should be updated accordingly.
After updating the configurePreset, we have to re-generate using the bang option as the new configurePreset might differ in the set cacheVariables and we have to get rid of the cached variables of the previous preset.
Question: should `select_configure_preset` use the bang option as per default as well? Keeping the `cacheVariables` values from the previous preset cached was unexpected to me 😅 
Fixes https://github.com/Civitasv/cmake-tools.nvim/issues/148#issue-1881394109
> update configurePreset when changing buildPreset

- lua/cmake-tools/init.lua
- lua/cmake-tools/presets.lua
Hey, this merge request contains 3 little fixes/features:
1. If cmakepreset has an include for a file, we should read the file as a relative path to the presets file
2. add option of `buildPreset=None` in case  the user wants to not use a build preset anymore
3. Changed the sourceDir expantion on presets.json to be "." instead of the supplied cwd. The reason is the sourceDir is relative to the presets file. And when we invoke cmake we already use the new cwd, so the source dir is the current dir. (Without this change, using `CMakeRun` with a preset file with another cwd does not work.
> Minor fixes - reading cmakepresets includes, add option to remove build preset and correct sourcedir on preset

- docs/cmake_kits.md
- lua/cmake-tools/config.lua
- lua/cmake-tools/executors/overseer.lua
- lua/cmake-tools/executors/terminal.lua
- lua/cmake-tools/executors/types.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/kits.lua
- lua/cmake-tools/quickfix.lua
- lua/cmake-tools/session.lua
- lua/cmake-tools/utils.lua
Added "environmentSetupScript" option in terminal execution. 
Does not yet work in overseer or quickfix list, but option is provided (I'm not sure how to use overseer 😅)
```json
{
"name": "Windows Clang 16.0",
"environmentSetupScript": "& \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\"",
"generator": "Ninja",
"linker" : "C:/Program Files/LLVM/bin/lld-link.exe",
"compilers": {
"C": "C:/Program Files/LLVM/bin/clang.exe",
"CXX": "C:/Program Files/LLVM/bin/clang.exe"
}
}
```
Ref: https://github.com/microsoft/vscode-cmake-tools/issues/809#issuecomment-662166588
---
Additionally, minor semantic terminal mode fixes.
> Experimental: Env Setup Script for terminal

- lua/cmake-tools/executors/overseer.lua
Temporarily fixing #158 and #159 by disabling envScript for overseer in preparation for #145 and #151
> Temp: Disable envScript in Overseer

- lua/cmake-tools/init.lua
Since 56b4c34 cwd selection is broken. Since this cwd selection is async, we should only regenerate when selection is finished. Otherwise the selection window will lose focus and the old cwd will get regenerated.
> Fix: Re-Generate CMake only after selection of cwd has finished

- lua/cmake-tools/init.lua
I noticed there isn't a simple way to cancel a running target, since the terminal is unmodified. This can be annoying when doing gui development as sometimes the exec loop is just running and you have no way to stop it.
I extended the `cmake.stop` function to stop any running terminals as well as executors.
Now when you run `:CmakeStop` it stops the running terminal too.
> Command CMakeStop now stops terminal processes as well

- lua/cmake-tools/kits.lua
I've never used kits and therefore don't have any of those files that are checked lying around.
At some point the plugin started to error out on CMakeGenerate/CMakeBuild commands.
I had a look and implemented a simple check whether a config file has been found.
> don't try to read kits when there is no file present

- README.md
- lua/cmake-tools/const.lua
- lua/cmake-tools/executors/terminal.lua
Added an option that disables sending the new line character when using `:CMakeRun` to give the user a chance to review and/or modify the command before it is executed.
> Option to review command executed by :CMakeRun

- lua/cmake-tools/presets.lua
A (build) preset might inherit from a preset without a configurePresets field set.
This causes p_preset to be nil when entering `helper`. The check for `not p_preset` does
not catch the unconditional access to `p_preset.name` resulting in an access to a nil variable
returning an empty string for a nil preset with the addtional nil check for the `ppreset` should
prevent the nil access.
The second commit is optional, but restructures the helper function a bit
> Fix: build dir for preset with inherited presets without configurePresets

- lua/cmake-tools/osys.lua
- lua/cmake-tools/session.lua
Adds support for *BSD systems by using the unix session directory structure.
Without this the plugin will crash on the FreeBSD install I'm using.
I wonder if it would make sense to have a generic `isunix` bool and use that in this check's place to handle more platforms that should be using the same directory structure.
Haven't tested if this has the same behaviour on Linux but at least on my FreeBSD machine `vim.fn.has("unix")` will return 1 as well, so that could be used as a catch all.
> Add support for *BSD

- README.md
- lua/cmake-tools/const.lua
- lua/cmake-tools/toggleterm.lua
As the name implies, uses a single instance of toggleterm by closing the already opened one.
Closes #209
> feat: add single_terminal_per_instance option for toggleterm

- lua/cmake-tools/test/ctest.lua
i saw the "depricated" commit, doesnt deprication mean that its a heads up before it gets removed?
> Fix call in ctest

- lua/cmake-tools/terminal.lua
this part is quite important expecially for tests because we want to get the exit code and delete lock even if command exits with an error code for example: when tests are failing and tests are made to fail
> fix: command not ending when cmd doesnt exit successfully

- lua/cmake-tools/utils.lua
i had to swap `"` to `'` because we wrap paths in `"`, this fixes symlink not being created if the path contains the space character
possibly wil fix [issue213](https://github.com/Civitasv/cmake-tools.nvim/issues/213)
> fix: transform path in utils.softlink()

- README.md
- lua/cmake-tools/config.lua
- lua/cmake-tools/const.lua
i added a very basic override when config is run on windows, didn't really know how to adnotate it properly in readme.
this should fix: [issue228](https://github.com/Civitasv/cmake-tools.nvim/issues/228),
if there will be a lot of mixed slashes errors for windows users we could add an slash check and replace in `utils.transform_path`
> feat: change default build path for windows

- lua/cmake-tools/terminal.lua
When the runner/executor is set to `terminal` the removal of the `.lock` file fails if the user has setup a shell alias for the `rm(1)` command that requires confirmation (e.g.: `alias rm='rm -iv'`).
In such case, the runner/executor does not finish and waits indefinitely for user confirmation: 
`remove ~/.local/share/nvim/cmake-tools-tmp/.lock?`
This PR bypasses any alias of `rm(1)` command and also uses the `-f` flag.
> fix(terminal): failure to remove .lock file

- lua/cmake-tools/quickfix.lua
When the runner/executor is set to `quickfix` and in the options `auto_close_when_success` is set to `false`, the `quickfix` window does not remain open.
This PR adds the missing check when success code = 0, auto close = false.
The issue is referenced also in the first bullet of https://github.com/Civitasv/cmake-tools.nvim/issues/201#issuecomment-2022290445
> fix(quickfix): auto_close_when_success false is ignored

- README.md
- docs/settings.md
- lua/cmake-tools/config.lua
- lua/cmake-tools/const.lua
- lua/cmake-tools/init.lua
On CMake projects that use Conan as their package manager, there are two presets that are created with the same name. This always causes any `cmake` command issued by CMakeTools to fail. On those scenarios, the project usually specify the CMake options (including the preset location) as an argument to the `cmake` command.
This commit adds the option to not pass the `--preset` argument to the `cmake` command.
> Add option to not pass the '--presets' option to the cmake command

- README.md
- lua/cmake-tools/const.lua
- lua/cmake-tools/terminal.lua
I'm not sure if the option name is fitting. I am open to suggestions.
Open question: Should the `keep_terminal_size` option be `true` per default?
> feat: add option to not resize the terminal (#247)

- lua/cmake-tools/init.lua
- lua/cmake-tools/scratch.lua
When starting vim in a project that has a top-level CMakeLists.txt in a subdirectory, then calling :CMakeSelectCwd {subdir} writing to the scratch buffer will fail because it doesn't exist yet. Make sure to register the buffer after changing cwd.
> fix: register scratch buffer after changing cwd

- lua/cmake-tools/init.lua
- lua/cmake-tools/notification.lua
- lua/cmake-tools/utils.lua
With the new approach we get rid of the global states managed in the notifications table. Everything is capsulated within the created notification instance.
That also allows to fix an issue where a notification is dismissed while a build process is still ongoing and the spinner should be updated. Updating the spinner fails, because the notification timed out and got dismissed, resulting in a repeating "No Matching notification to replace found" error.
The new instance based approach tracks the shown notification and replaces any existing notification when the message is updated. If the notification times out and is dismissed, the instance will create a new notification automatically.
Additionally, the notification window is resized automatically to match the updated contents, if the …
> feat: improve runner and executer notification handling

- lua/cmake-tools/init.lua
- lua/cmake-tools/result.lua
- lua/cmake-tools/types.lua
- lua/cmake-tools/utils.lua
In this PR I add callback(result) as the last parameter to most API calls, and:
1. Make sure it is always called exactly once, be that in case of success or failure
2. Fix a bug with `Result` type: its `new` method was setting attributes on the class instead of the object
3. Fix a bug with `Types` type: `SUCCESS` was `1` when there are places in code that assume that it is 0
4. Add a couple of error messages
I tested this locally - to an extent, let me know if there is some kind of proper procedure to know it's working.
RESOLVES: #245
> feat!(API): add callback(result) to lua API

- docs/cmake_presets.md
- lua/cmake-tools/config.lua
- lua/cmake-tools/const.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/preset.lua
- lua/cmake-tools/presets.lua
This PR comes with an overhaul of the preset parsing / handling. 
It contains the followin changes:
This is the enablement for the other features contained in the PR. 
As the configure preset data is now encapsulated in the class instance, it is not necessary to read the preset file(s) multiple times to access different parts of the preset. 
Previously, the most extreme case was determining the build_dir, which read the preset file for each inherited preset.
The new approach reads the file exactly once and parses the data into a hierarchy of preset instances.
If a CMakeUserPreset.json is found, the old implementation did not look up neither the inherited presets nor non-hidden presets from a CMakePreset.json file.
The new implementation reads both files and combines them into one data …
> Presets refactoring

- lua/cmake-tools/init.lua
append the `build_options` args last so that passing `"--", "<some backend arg>"` works correctly
Fix for #249 & #261
> append `build_options` last so backend args pass correctly

- lua/cmake-tools/const.lua
- lua/cmake-tools/terminal.lua
Using an alias allows hiding the lengthy details needed to run the built target.
It also hides the used workaround to catch the command's return code and keeps the command line clean.
Currently this PR does not target windows as I do not have a setup to test a possible implementation. 
I think it should work similar to this PR's approach by using `DOSKEY` tho. 
I am not sure, if the current alias name is the best choice - I am open for suggestions.
Optionally, it could be made configurable by the user.
> feat(terminal): add option to use an alias for terminal runner

- lua/cmake-tools/const.lua
cb7dc21a6da58f improved the defaults for overseer, but omitted to set actually set on_new_task to the value stated in the README.
> fix: Change defaults to match README

- lua/cmake-tools/init.lua
On Windows, nvim interprets `\2024` in paths like `C:\foo\2024` as a regex back reference,
causing issues. fixes https://github.com/Civitasv/cmake-tools.nvim/issues/239
> fix: replace backslashes on Windows for pattern

- lua/cmake-tools/preset.lua
[Ref](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_NAME.html)
> fix: incorrect macro expansion for `$(hostSystemName}` on Windows

- lua/cmake-tools/terminal.lua
`&' is not powershell's chain symbol, but the `;` symbol.
> feat: using correct shell chain symbol for windows powershell (#262)

- lua/cmake-tools/terminal.lua
The windows powershell legacy ( version 5.1 that come default with windows) does not have the `&&` operator which cause `CMakeRun` command error:
```
C:\Users\Michael\projects\cpp\DSA> cmd /C "cd C:\Users\Michael\projects\cpp\DSA\./build\Pro\Bacteria\ && .\Bacteria.exe"; echo $LASTEXITCODE > C:\Users\Michael\AppData\Local\nvim-data
\cmake-tools-tmp\exit_code && Remove-Item C:\Users\Michael\AppData\Local\nvim-data\cmake-tools-tmp\.lock 
At line:1 char:176
+ ... \Michael\AppData\Local\nvim-data\cmake-tools-tmp\exit_code && Remove- ...
+                                                                ~~
The token '&&' is not a valid statement separator in this version.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvalidEndOfLine …
```
> fix(windows): Fix powershell legacy and operator `&&`

- lua/cmake-tools/init.lua
Multiconfig generators like ninja need the build type passed at the build stage and not the configure stage.
> fix: pass config argument to build process for multiconfig generators

- README.md
cmake-tools.nvim requires `setup()` to be called to work properly
This addresses #288
> update lazy.nvim setup instruction in README

- lua/cmake-tools/preset.lua
With the current implementation, if CMakePresets.json sets CMAKE_BUILD_TYPE as a JSON object with a "type" and "value", then it causes the build/configuration fail -- example below.
```json
"CMAKE_BUILD_TYPE": {
"type": "STRING",
"value": "Debug"
}
```
This fix looks for a CMAKE_BUILD_TYPE with a "table" type and extracts the "value" element, otherwise it falls back to the original behavior.
> Add support for CMAKE_BUILD_TYPE presets using "type"/"value" form.

- lua/cmake-tools/init.lua
- lua/cmake-tools/utils.lua
When running a specific target (e.g. `CMakeQuickRun`) there might not be a `target_settings` config available. Previously the `target_settings` of that target were always accessed assuming it was there.
Now each access is checked and an empty table is used as a fallback.
Feel free to make any changes or suggestions!
> fix: Indexing a nil value when no target launch settings are configured

- lua/cmake-tools/utils.lua
The new feature cmake_use_scratch_buffer lets user can decide whether to use the scratch buffer. @Civitasv ensures that the scratch is created only when cmake_use_scratch_buffer is true. But no matter whether this scratch buffer is created, scratch.append would be called when new operation is performed.
Thus, I add a check to ensure that scratch.append would be called only when scratch buffer exists.
> fix: only append when scratch.buffer is not nil

- lua/cmake-tools/config.lua
When executing a :CMakeRun with the build type of "Release", the target is attempted to be executed from the nonexistent "\Release\Debug\" directory.
```
C:\Users\uttervitriol\source\repos\learn_cmake>cmd /C "cd C:\Users\uttervitriol\source\repos\learn_cmake\out\Release\Debug\ && .\DoThing.exe
"& echo %errorlevel% > C:\Users\uttervitriol\AppData\Local\nvim-data\cmake-tools-tmp\exit_code && del /Q C:\Users\uttervitriol\AppData\Local
\nvim-data\cmake-tools-tmp\.lock
The system cannot find the path specified.
```
After looking into it, it seems that the function Config:get_codemodel_targets() contains the bug producing this error.
The file (path_to_cmake)/out/(Release/Debug/etc)/.cmake/api/v1/replycodmodel.....json contains a key "configurations" whose value is an array of configurations for …
> fix: CMakeRun defaults to Debug configuration regardless of build type.

- lua/cmake-tools/notification.lua
if the window has not yet been opened, the winID is not set. Passing a nil value to nvim_win_is_valid returns an error instead of false
> fix(notification): nvim_win_is_valid does not accepts nil

- lua/cmake-tools/build_preset.lua
- lua/cmake-tools/config.lua
- lua/cmake-tools/init.lua
If a build preset from CMakePresets.json contained multiple targets, `BuildPreset:get_build_target` would concatenate target names into a single string which would be used as a single command line argument. The build system, such as Ninja, would then complain that the specified target is unknown.
This change modifies `BuildPreset:get_build_target` to return a table of targets instead, which is then unpacked after CMake's `--target` flag. That way, each target is a separate command line argument and the build system executes a proper multi-target build.
> Fix build presets with multiple targets

- lua/cmake-tools/build_preset.lua
- lua/cmake-tools/init.lua
- lua/cmake-tools/presets.lua
This commit changes the handling of the None option of the build-preset selection to be an actual preset. A new `is_valid` function checks if the preset was created from the presets file or if it was added "by hand" for the option to have no (real) build-preset selected
> refactor(build-preset): make 'None' option an actual preset (#333)

- lua/cmake-tools/terminal.lua
This places the exit_handler inside the quotes, so the exit handler will be included in the `cmd /C`
> Fix windows terminal cmd quote placement
